sudo: true
dist: trusty

env:
    - LLVM_SYS_60_STRICT_VERSIONING=1 LLVM_SYS_60_PREFIX=/usr/lib/llvm-6.0

language: rust

rust:
    - stable
    - nightly

cache:
    - cargo

script:
    - cargo build
    - cargo build --release
    - cargo test

addons:
    apt:
        sources:
            - llvm-toolchain-trusty-6.0
        packages:
            - llvm-6.0-dev
